version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: example123
      POSTGRES_DB: "ReverseTask"
      POSTGRES_USER: "postgres"


  app:
    container_name: ReverseTask
    build:
      context: .
      dockerfile: ReverseTask/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      DB_CONNECTION_STRING: "host=db;port=15432;database=ReverseTask;username=postgres;password=example123"

